# Generated by Django 4.2.14 on 2024-07-18 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('Creation', models.DateTimeField(auto_now_add=True)),
                ('Creation_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('Meals', '餐飲費'), ('transportation', '交通'), ('groceries', '購物'), ('entertainment', '娛樂'), ('apparel', '衣服'), ('Pay', '繳費'), ('other', '其他')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
